server:
  port: 8888
spring:
  datasource:
    username: root
    password: 890828
    url: jdbc:mysql://101.132.154.224:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      content-type: text/html
    enabled: true
    encoding: UTF-8
    mode: HTML5
  redis:
    database: 0
    timeout: 0
    port: 6379
    host: 101.132.154.224
    password: 890828
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
    rabbitmq:
      host: 101.132.154.224
      password: admin
      username: admin
      listener:
        simple:
          retry:
            enabled: true
            max-attempts: 3
            initial-interval: 3000
          default-requeue-rejected: true

mybatis:
  type-aliases-package: com.example.miaosha.model
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/example/miaosha/dao/*.xml


